CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
DROP TABLE IF EXISTS PESSOAS;

CREATE TABLE IF NOT EXISTS PESSOAS(
    id TEXT DEFAULT UUID_GENERATE_V4(),
    apelido TEXT NOT NULL UNIQUE,
    nome TEXT NOT NULL,
    nascimento TEXT,
    stack TEXT DEFAULT NULL
);