CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
DROP TABLE IF EXISTS PESSOAS;

CREATE TABLE IF NOT EXISTS PESSOAS(
    id TEXT DEFAULT UUID_GENERATE_V4(),
    apelido TEXT NOT NULL UNIQUE,
    nome TEXT NOT NULL,
    nascimento TEXT,
    stack TEXT DEFAULT NULL,
    termodebusca TEXT DEFAULT NULL
);

CREATE INDEX IDX_TERMO_PESSOA ON PESSOAS(termodebusca);
CREATE INDEX IDX_APELIDO_PESSOA ON PESSOAS(apelido);
CREATE INDEX IDX_ID_PESSOA ON PESSOAS(id);